### ISSUE TITLE
The query sequence returned by '%s' is not the same of the original one.

### ISSUE THREAD

**Issue by xjllh** [pymodproject/pymod#12]
The sequence cannot be displayed in the SEQUENCE ID and SEQUENCES sections after submitting the selected sequence when running NCBI BLAST using pymod 3.0.2. Simultaneously, an error occurs in PyMol, and the traceback is as follows:
Traceback (most recent call last):
  File "D:\pymol\pymol_edu\pymol_edu_install\lib\site-packages\pmg_tk\startup\pymod3\pymod_lib\pymod_protocols\similarity_searches_protocols\_base_blast.py", line 879, in <lambda>
    self.main_button.clicked.connect(lambda a=None: self.protocol.blast_results_state())
  File "D:\pymol\pymol_edu\pymol_edu_install\lib\site-packages\pmg_tk\startup\pymod3\pymod_lib\pymod_protocols\similarity_searches_protocols\_base_blast.py", line 445, in blast_results_state
    self.import_results_in_pymod()
  File "D:\pymol\pymol_edu\pymol_edu_install\lib\site-packages\pmg_tk\startup\pymod3\pymod_lib\pymod_protocols\similarity_searches_protocols\_base_blast.py", line 583, in import_results_in_pymod
    raise Exception("The query sequence returned by '%s' is not the same of the original one." % self.blast_version)
Exception: The query sequence returned by 'blast' is not the same of the original one.
![1](https://github.com/pymodproject/pymod/assets/129521592/59adb878-d895-48ee-9569-6f9bc08be146)
![2](https://github.com/pymodproject/pymod/assets/129521592/bf9ae751-bf20-4f67-871f-180071e5f943)

**Comment by irisdisilverio** [comment]
Could you tell me which sequence did you use?
To solve the issue, try performing remote BLAST using SwissProt as database or try running the BLAST locally, since there might be an issue with the NCBI server.
